// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package core

import (
	"encoding/json"
	"math/big"

	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/common/math"
)

var _ = (*initMarshaling)(nil)

// MarshalJSON marshals as JSON.
func (i Init) MarshalJSON() ([]byte, error) {
	type Init struct {
		Admin           common.Address        `json:"admin,omitempty"`
		FirstLockPeriod *math.HexOrDecimal256 `json:"firstLockPeriod,omitempty"`
		ReleasePeriod   *math.HexOrDecimal256 `json:"releasePeriod,omitempty"`
		ReleaseCnt      *math.HexOrDecimal256 `json:"releaseCnt,omitempty"`
		RuEpoch         *math.HexOrDecimal256 `json:"ruEpoch,omitempty"`
		PeriodTime      *math.HexOrDecimal256 `json:"periodTime,omitempty"`
		LockedAccounts  []LockedAccount       `json:"lockedAccounts,omitempty"`
	}
	var enc Init
	enc.Admin = i.Admin
	enc.FirstLockPeriod = (*math.HexOrDecimal256)(i.FirstLockPeriod)
	enc.ReleasePeriod = (*math.HexOrDecimal256)(i.ReleasePeriod)
	enc.ReleaseCnt = (*math.HexOrDecimal256)(i.ReleaseCnt)
	enc.RuEpoch = (*math.HexOrDecimal256)(i.RuEpoch)
	enc.PeriodTime = (*math.HexOrDecimal256)(i.PeriodTime)
	enc.LockedAccounts = i.LockedAccounts
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (i *Init) UnmarshalJSON(input []byte) error {
	type Init struct {
		Admin           *common.Address       `json:"admin,omitempty"`
		FirstLockPeriod *math.HexOrDecimal256 `json:"firstLockPeriod,omitempty"`
		ReleasePeriod   *math.HexOrDecimal256 `json:"releasePeriod,omitempty"`
		ReleaseCnt      *math.HexOrDecimal256 `json:"releaseCnt,omitempty"`
		RuEpoch         *math.HexOrDecimal256 `json:"ruEpoch,omitempty"`
		PeriodTime      *math.HexOrDecimal256 `json:"periodTime,omitempty"`
		LockedAccounts  []LockedAccount       `json:"lockedAccounts,omitempty"`
	}
	var dec Init
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.Admin != nil {
		i.Admin = *dec.Admin
	}
	if dec.FirstLockPeriod != nil {
		i.FirstLockPeriod = (*big.Int)(dec.FirstLockPeriod)
	}
	if dec.ReleasePeriod != nil {
		i.ReleasePeriod = (*big.Int)(dec.ReleasePeriod)
	}
	if dec.ReleaseCnt != nil {
		i.ReleaseCnt = (*big.Int)(dec.ReleaseCnt)
	}
	if dec.RuEpoch != nil {
		i.RuEpoch = (*big.Int)(dec.RuEpoch)
	}
	if dec.PeriodTime != nil {
		i.PeriodTime = (*big.Int)(dec.PeriodTime)
	}
	if dec.LockedAccounts != nil {
		i.LockedAccounts = dec.LockedAccounts
	}
	return nil
}
